#Honor Pledge
#
#I peldge that I have neither given nor
#received any help on this assignment.
#
#jeremorg

all: Driver.class Stack.class

Driver.class: Driver.java
	javac Driver.java
	
Stack.class: Stack.java
	javac Stack.java
	
clean:
	rm *.class
	
run: java Driver
